CREATE TABLE IF NOT EXISTS public.tab_caixa
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nome text COLLATE pg_catalog."default" NOT NULL,
    data date NOT NULL,
    CONSTRAINT tab_caixa_pkey PRIMARY KEY (id)
)

CREATE TABLE IF NOT EXISTS public.tab_extrato_caixa
(
    id serial NOT NULL ,
    id_venda integer NOT NULL,
    hora time without time zone NOT NULL,
    cash double precision NOT NULL,
    card double precision NOT NULL,
    CONSTRAINT tab_dados_pkey PRIMARY KEY (id),
    CONSTRAINT tab_extrato_caixa_relation_1 FOREIGN KEY (id_venda)
        REFERENCES public.tab_caixa (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

CREATE TABLE IF NOT EXISTS public.tab_autorizacao
(
    id serial NOT NULL,
    autorizedby character varying(255) COLLATE pg_catalog."default" NOT NULL,
    operacao character varying(255) COLLATE pg_catalog."default" NOT NULL,
    datahora timestamp without time zone NOT NULL,
    CONSTRAINT tab_autorizacao_pkey PRIMARY KEY (id)
)


CREATE TABLE IF NOT EXISTS public.tab_carinho
(
    id serial NOT NULL,
    numero integer NOT NULL,
    CONSTRAINT tab_carinho_pkey PRIMARY KEY (id)
)
CREATE TABLE IF NOT EXISTS public.tab_customer
(
    id serial NOT NULL,
    empresa character varying(255) COLLATE pg_catalog."default" NOT NULL,
    nuit integer,
    endereco character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT tab_customer_pkey PRIMARY KEY (id)
)

CREATE TABLE IF NOT EXISTS public.tab_dadosclientecard
(
    id_venda serial NOT NULL,
    data timestamp without time zone NOT NULL,
    idrecibo text COLLATE pg_catalog."default" NOT NULL,
    nrpos integer,
    expdate integer,
    card integer,
    valor integer NOT NULL,
    CONSTRAINT tab_dadosclientecard_pkey PRIMARY KEY (id_venda)
)
CREATE TABLE IF NOT EXISTS public.tab_entrada_stock
(
    id serial NOT NULL,
    autorizedby character varying(255) COLLATE pg_catalog."default" NOT NULL,
    operacao character varying(255) COLLATE pg_catalog."default" NOT NULL,
    datahora timestamp without time zone NOT NULL,
    produto integer NOT NULL,
    qtdanterior double precision NOT NULL,
    qtdatual double precision NOT NULL,
    CONSTRAINT tab_entrada_stock_pkey PRIMARY KEY (id)
)
CREATE TABLE IF NOT EXISTS public.tab_fecho
(
    id serial NOT NULL,
    nome text COLLATE pg_catalog."default" NOT NULL,
    data timestamp without time zone NOT NULL,
    valor_total double precision NOT NULL,
    valor_falta double precision NOT NULL,
    CONSTRAINT tab_fecho_pkey PRIMARY KEY (id)
)
CREATE TABLE IF NOT EXISTS public.tab_log_de_login
(
    id serial NOT NULL,
    nome_completo text COLLATE pg_catalog."default" NOT NULL,
    data_hora_login timestamp without time zone NOT NULL,
    CONSTRAINT tab_log_de_login_pkey PRIMARY KEY (id)
)
CREATE TABLE IF NOT EXISTS public.tab_notas
(
    id serial NOT NULL,
    id_fecho integer NOT NULL,
    card double precision NOT NULL,
    n1000 integer NOT NULL,
    n500 integer NOT NULL,
    n200 integer NOT NULL,
    n100 integer NOT NULL,
    n50 integer NOT NULL,
    n20 integer NOT NULL,
    moedas double precision NOT NULL,
    CONSTRAINT tab_notas_pkey PRIMARY KEY (id),
    CONSTRAINT tab_notas_relation_1 FOREIGN KEY (id_fecho)
        REFERENCES public.tab_fecho (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
CREATE TABLE IF NOT EXISTS public.tab_produtos
(
    id serial NOT NULL,
    codigo integer NOT NULL,
    descricao text COLLATE pg_catalog."default" NOT NULL,
    stock_loja double precision,
    stock_armazem double precision NOT NULL,
    preco double precision NOT NULL,
    preco_venda double precision NOT NULL,
    imagem bytea,
    type character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tab_produtos_pkey PRIMARY KEY (id)
)

CREATE TABLE IF NOT EXISTS public.tab_return
(
    id serial NOT NULL,
    iddatroca text COLLATE pg_catalog."default" NOT NULL,
    datahora timestamp without time zone NOT NULL,
    autorizadopor text COLLATE pg_catalog."default" NOT NULL,
    operador text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tab_return_pkey PRIMARY KEY (id)
)

CREATE TABLE IF NOT EXISTS public.tab_produtos_devolvidos
(
    id serial NOT NULL,
    id_venda integer NOT NULL,
    codigo integer NOT NULL,
    descricao text COLLATE pg_catalog."default" NOT NULL,
    quantidade double precision NOT NULL,
    preco double precision NOT NULL,
    subtotal double precision NOT NULL,
    CONSTRAINT tab_produtos_devolvidos_pkey PRIMARY KEY (id),
    CONSTRAINT tab_produtos_devolvidos_relation_2 FOREIGN KEY (id_venda)
        REFERENCES public.tab_return (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)
CREATE TABLE IF NOT EXISTS public.tab_produtos_promocao
(
    id serial NOT NULL,
    codigo_do_produto numeric NOT NULL,
    preco_normal numeric NOT NULL,
    preco_promocional numeric NOT NULL,
    data_fim_promocao date,
    data_inicio_promocao date,
    CONSTRAINT tab_produtos_promocao_pkey PRIMARY KEY (id),
    CONSTRAINT codigo_do_produto_unique UNIQUE (codigo_do_produto)
)
CREATE TABLE IF NOT EXISTS public.tab_produtos_salvos
(
    id serial NOT NULL,
    id_carrinho integer NOT NULL,
    codigo integer NOT NULL,
    descricao text COLLATE pg_catalog."default" NOT NULL,
    quantidade double precision NOT NULL,
    preco real NOT NULL,
    subtotal double precision NOT NULL,
    CONSTRAINT tab_produtos_salvos_pkey PRIMARY KEY (id),
    CONSTRAINT tab_produtos_salvos_relation_1 FOREIGN KEY (id_carrinho)
        REFERENCES public.tab_carinho (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)
CREATE TABLE IF NOT EXISTS public.tab_vendas
(
    id_venda serial NOT NULL,
    id_recibo text COLLATE pg_catalog."default" NOT NULL,
    data_venda timestamp without time zone NOT NULL,
    operador text COLLATE pg_catalog."default" NOT NULL,
    valor_total double precision NOT NULL,
    CONSTRAINT tab_vendas_pkey PRIMARY KEY (id_venda)
)


CREATE TABLE IF NOT EXISTS public.tab_produtos_vendidos
(
    id_produto serial NOT NULL,
    id_venda integer NOT NULL,
    codigo integer NOT NULL,
    descricao text COLLATE pg_catalog."default" NOT NULL,
    quantidade double precision NOT NULL,
    preco double precision NOT NULL,
    subtotal double precision NOT NULL,
    CONSTRAINT tab_produtos_vendidos_pkey PRIMARY KEY (id_produto),
    CONSTRAINT tab_produtos_vendidos_relation_2 FOREIGN KEY (id_venda)
        REFERENCES public.tab_vendas (id_venda) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)


CREATE TABLE IF NOT EXISTS public.tab_users
(
    id_user serial NOT NULL,
    username text COLLATE pg_catalog."default" NOT NULL,
    nome_utilizador text COLLATE pg_catalog."default" NOT NULL,
    senha text COLLATE pg_catalog."default" NOT NULL,
    acesso_caixa boolean,
    acesso_gestao boolean,
    acesso_contabilista boolean,
    acesso_admin boolean,
    CONSTRAINT tab_users_pkey PRIMARY KEY (id_user)
)
