package mz.co.fer.View;

import mz.co.fer.DAO.UtilizadorDAO;
import mz.co.fer.DTO.AuthService;
import mz.co.fer.DTO.Utilizador;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import mz.co.fer.DAO.FechoDAO;
import mz.co.fer.DAO.LogsDAO;
import mz.co.fer.DTO.Logs;

/**
 *
 *
 * @author Fernando
 */
public class FrmLogin extends javax.swing.JFrame {

    public FrmLogin() {
        initComponents();
        this.setSize(359, 333);
        setLocationRelativeTo(null);

        ImageIcon icon = new ImageIcon(getClass().getResource("/Images/shopping-cart-16.png"));
        this.setIconImage(icon.getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jbtEntrar = new javax.swing.JButton();
        txtSenha = new javax.swing.JPasswordField();
        txtUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login ao Sistema");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(102, 102, 102));
        setResizable(false);
        getContentPane().setLayout(null);

        jbtEntrar.setText("Entrar");
        jbtEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtEntrar);
        jbtEntrar.setBounds(230, 211, 71, 34);

        txtSenha.setToolTipText("Introduza a senha");
        txtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(txtSenha);
        txtSenha.setBounds(80, 171, 218, 22);

        txtUser.setToolTipText("Introduza o username");
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        getContentPane().add(txtUser);
        txtUser.setBounds(80, 103, 218, 22);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Password:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 143, 80, 20);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Username:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 74, 83, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 360, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEntrarActionPerformed
        try {
            String nome_usuario, senha_usuario;
            nome_usuario = txtUser.getText();
            senha_usuario = String.valueOf(txtSenha.getPassword());

            Utilizador obUserDto = new Utilizador();
            obUserDto.setUsername(nome_usuario);
            obUserDto.setSenha(senha_usuario);

            UtilizadorDAO objUserDao = new UtilizadorDAO();
            ResultSet rsuserdao = objUserDao.autenticacaoDoUtilizador(obUserDto);

            if (rsuserdao.next()) {
                String nomeCompleto = objUserDao.procurarNomeCompleto(nome_usuario);
                Logs log = new Logs(nomeCompleto);
                LogsDAO logDAO = new LogsDAO();
                logDAO.save(log); //Salva a data e hora do login
                AuthService.setCurrentUser(nomeCompleto);
                //Server.addUser(nomeCompleto);
                Utilizador utilizador = UtilizadorDAO.procurarUtilizadorPeloNome(nomeCompleto);
                if (utilizador.isAcessoContabilista() || utilizador.isAcessoGestao() || utilizador.isAcessoAdmin()) {
                    FrmMenu menu = new FrmMenu();
                    menu.setIconImage(this.getIconImage());
                    menu.setVisible(true);
                    dispose();
                } else if (utilizador.isAcessoCaixa()) {
                    FechoDAO fechoDAO = new FechoDAO();
                    boolean fechoRealizado = fechoDAO.verificarFecho(nomeCompleto);

                    if (fechoRealizado) {
                        JOptionPane.showMessageDialog(this, "Utilizador não pode vender. Fecho do dia já realizado.", "Atenção", JOptionPane.WARNING_MESSAGE);
                    } else {
                        FrmCaixa caixa = new FrmCaixa();
                        caixa.setIconImage(this.getIconImage());
                        caixa.setVisible(true);
                        dispose();
                    }

                }

            } else {
                JOptionPane.showMessageDialog(this, "Nome de Utilizador ou Senha Inválidos!", "Atenção", JOptionPane.WARNING_MESSAGE);
            }

        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(this, "Error" + erro);
        }
    }//GEN-LAST:event_jbtEntrarActionPerformed

    private void txtSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ActionEvent evtt = null;
            jbtEntrarActionPerformed(evtt);
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            txtUser.requestFocus();
        }
    }//GEN-LAST:event_txtSenhaKeyPressed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed

        txtSenha.requestFocus();

    }//GEN-LAST:event_txtUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmLogin().setVisible(true);
            //new FrmLogin().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbtEntrar;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

}
