package mz.co.fer.View;

import mz.co.fer.DAO.ProdutoDAO;
import mz.co.fer.DTO.Produto;
import mz.co.fer.Relatorios.GerarPDF;
import mz.co.fer.Outros.Tables;
import com.itextpdf.text.DocumentException;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Deockilion
 */
public class FrmRequisicao extends javax.swing.JDialog {

    /**
     * Creates new form ViewRequisicao
     *
     * @param parent
     * @param modal
     */
    public FrmRequisicao(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(680, 500);
        setLocationRelativeTo(null);
        txtCod.setEditable(false);
        txtPreco.setEditable(false);
        txtDesc.setEditable(false);
        txtQtd.setEditable(false);
        jbtAdd.setEnabled(false);
        jtfCodPrice.requestFocus();
    }

    private void inserirProdTabela(float quantidade) {
        String codProduto = jtfCodPrice.getText();
        int codigoProduto = Integer.parseInt(codProduto);

        ProdutoDAO produtoDAO = new ProdutoDAO();
        Produto produto = produtoDAO.retornarProduto(codigoProduto);
        DefaultTableModel modelo = (DefaultTableModel) jTprodPrecos.getModel();

        if (produto != null) {
            if (produto.getType().equals("UNIDADE") && quantidade != Math.floor(quantidade)) {
                JOptionPane.showMessageDialog(this, "Este produto é por unidade, insira uma quantidade inteira.");
            } else {
                double subtotal = quantidade * produto.getPrecoVenda();
                modelo.addRow(new Object[]{
                    produto.getCodigo(),
                    produto.getDescricao(),
                    quantidade,
                    produto.getPrecoVenda(),
                    subtotal
                });
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFornecedor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNuit = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTprodPrecos = new javax.swing.JTable();
        jtfCodPrice = new javax.swing.JTextField();
        jbtprintPreco = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jCoBoxRequisicao = new javax.swing.JComboBox<>();
        jbtNovo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDesc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtQtd = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        jbtAdd = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Requisição de Produtos");
        setModal(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Fornecedor:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(12, 54, 67, 16);

        txtFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFornecedorActionPerformed(evt);
            }
        });
        getContentPane().add(txtFornecedor);
        txtFornecedor.setBounds(80, 51, 108, 22);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("NUIT:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(12, 95, 32, 16);

        txtNuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuitActionPerformed(evt);
            }
        });
        getContentPane().add(txtNuit);
        txtNuit.setBounds(80, 92, 108, 22);

        jTprodPrecos.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTprodPrecos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descrição", "Quantidade", "Preço Unit.", "SubTotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTprodPrecos);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(12, 134, 622, 258);

        jtfCodPrice.setToolTipText("Digite o código do produto.");
        jtfCodPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCodPriceKeyPressed(evt);
            }
        });
        getContentPane().add(jtfCodPrice);
        jtfCodPrice.setBounds(12, 410, 111, 22);

        jbtprintPreco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/print-16.png"))); // NOI18N
        jbtprintPreco.setText("Imprimir");
        jbtprintPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtprintPrecoActionPerformed(evt);
            }
        });
        getContentPane().add(jbtprintPreco);
        jbtprintPreco.setBounds(535, 410, 99, 25);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/remove-16.png"))); // NOI18N
        jButton4.setText("Remover");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(343, 410, 99, 25);

        jButton5.setText("Limpar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(454, 410, 69, 25);

        jCoBoxRequisicao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Requisição", "Cotação" }));
        getContentPane().add(jCoBoxRequisicao);
        jCoBoxRequisicao.setBounds(12, 20, 176, 22);

        jbtNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/novo-foco.png"))); // NOI18N
        jbtNovo.setText("Novo");
        jbtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNovoActionPerformed(evt);
            }
        });
        getContentPane().add(jbtNovo);
        jbtNovo.setBounds(256, 19, 90, 25);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Codigo");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(256, 54, 39, 16);

        txtCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodActionPerformed(evt);
            }
        });
        getContentPane().add(txtCod);
        txtCod.setBounds(325, 51, 109, 22);

        jLabel4.setText("Descrição");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(256, 95, 51, 16);

        txtDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescActionPerformed(evt);
            }
        });
        getContentPane().add(txtDesc);
        txtDesc.setBounds(325, 92, 109, 22);

        jLabel5.setText("QTD:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(452, 54, 26, 16);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Preço:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(452, 95, 33, 16);

        txtQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtdActionPerformed(evt);
            }
        });
        getContentPane().add(txtQtd);
        txtQtd.setBounds(496, 51, 65, 22);

        txtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoActionPerformed(evt);
            }
        });
        getContentPane().add(txtPreco);
        txtPreco.setBounds(497, 92, 64, 22);

        jbtAdd.setText("Add");
        jbtAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAddActionPerformed(evt);
            }
        });
        getContentPane().add(jbtAdd);
        jbtAdd.setBounds(579, 91, 55, 25);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rotacao-de-stock-como-afeta-armazem-1024x538.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, -4, 790, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfCodPriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodPriceKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                float quant = Float.parseFloat(JOptionPane.showInputDialog(this, "Introduza a quantidade", "Mensagem", JOptionPane.INFORMATION_MESSAGE));

                if (quant < 0) {
                    JOptionPane.showMessageDialog(this, "Introduza um valor positivo!", "Atenção", JOptionPane.WARNING_MESSAGE);

                } else {
                    inserirProdTabela(quant);
                }

                jtfCodPrice.setText("");
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Código do produto inválido. Insira um número válido!");
            }
        }
    }//GEN-LAST:event_jtfCodPriceKeyPressed

    private void jbtprintPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtprintPrecoActionPerformed
        try {
            String requisicao = (String) jCoBoxRequisicao.getSelectedItem();
            if (!txtFornecedor.getText().isEmpty() && !txtNuit.getText().isEmpty()) {
                DefaultTableModel modelo = (DefaultTableModel) jTprodPrecos.getModel();
                new GerarPDF().gerarRequisicao(modelo, txtFornecedor.getText().toUpperCase(), txtNuit.getText(), requisicao);
                txtFornecedor.setText("");
                txtNuit.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "O nome do Fornecedor e NUIT não podem ser nulos!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (DocumentException | IOException ex) {
            Logger.getLogger(FrmRequisicao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtprintPrecoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new Tables().removerLinhaSelecionada(jTprodPrecos);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new Tables().limparTabela(jTprodPrecos);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFornecedorActionPerformed
        txtNuit.requestFocus();
    }//GEN-LAST:event_txtFornecedorActionPerformed

    private void txtNuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuitActionPerformed
        jtfCodPrice.requestFocus();
    }//GEN-LAST:event_txtNuitActionPerformed

    private void jbtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNovoActionPerformed
        txtCod.setEditable(true);
        txtPreco.setEditable(true);
        txtDesc.setEditable(true);
        txtQtd.setEditable(true);
        jbtAdd.setEnabled(true);
    }//GEN-LAST:event_jbtNovoActionPerformed

    private void jbtAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAddActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jTprodPrecos.getModel();

        try {
            int codigo = txtCod.getText().trim().isEmpty() ? 0 : Integer.parseInt(txtCod.getText());
            String descricao = txtDesc.getText();
            float qtd = Float.parseFloat(txtQtd.getText());
            double preco = Double.parseDouble(txtPreco.getText());
            double subtotal = qtd * preco;
            if (!descricao.isEmpty()) {
                modelo.addRow(new Object[]{
                    codigo,
                    descricao,
                    qtd,
                    preco,
                    subtotal
                });
                txtCod.setText("");
                txtDesc.setText("");
                txtQtd.setText("");
                txtPreco.setText("");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jbtAddActionPerformed

    private void txtCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodActionPerformed
        txtDesc.requestFocus();
    }//GEN-LAST:event_txtCodActionPerformed

    private void txtDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescActionPerformed
        txtQtd.requestFocus();
    }//GEN-LAST:event_txtDescActionPerformed

    private void txtQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtdActionPerformed
        txtPreco.requestFocus();
    }//GEN-LAST:event_txtQtdActionPerformed

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
        jbtAddActionPerformed(evt);
    }//GEN-LAST:event_txtPrecoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jCoBoxRequisicao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTprodPrecos;
    private javax.swing.JButton jbtAdd;
    private javax.swing.JButton jbtNovo;
    private javax.swing.JButton jbtprintPreco;
    private javax.swing.JTextField jtfCodPrice;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtFornecedor;
    private javax.swing.JTextField txtNuit;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQtd;
    // End of variables declaration//GEN-END:variables
}
