package mz.co.fer.View;

import mz.co.fer.DAO.FechoDAO;
import mz.co.fer.DTO.Fecho;
import mz.co.fer.DTO.Notas;
import java.time.Instant;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.DocFlavor;
import javax.print.DocPrintJob;
import javax.print.PrintException;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.print.SimpleDoc;
import javax.swing.JOptionPane;

/**
 *
 * @author Deockilion
 */
public class FrmUpdateFecho extends javax.swing.JDialog {

    private int valor1000;
    private int valor500;
    private int valor200;
    private int valor100;
    private int valor50;
    private int valor20;
    private double cartoes;
    private float moeda;
    private String nome;
    private double total;
    private int id;
    private int idn;
    Date dataHoraAtual = Date.from(Instant.now());

    /**
     * Creates new form SetarFecho
     *
     * @param parent
     * @param modal
     */
    public FrmUpdateFecho(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }
    private void sentToPrinter(double card, Notas nota, double diferenca) {
        try {
            StringBuilder content = new StringBuilder();
            content.append("-----------------------------------\n");
            content.append("           Fecho do Dia            \n");
            content.append("-----------------------------------\n");
            content.append("Data: ").append(dataHoraAtual).append("\n");
            content.append("Nome: ").append(txtNomeCom.getText()).append("\n");
            content.append("-----------------------------------\n");
            content.append("CARTÃO: ").append(card).append("\n");
            content.append("Cartão: ").append(cartoes).append("\n");
            content.append("-----------------------------------\n");
            content.append("1000: ").append(nota.getV1000()).append("\n");
            content.append("500: ").append(nota.getV500()).append("\n");
            content.append("200: ").append(nota.getV200()).append("\n");
            content.append("100: ").append(nota.getV100()).append("\n");
            content.append("50: ").append(nota.getV50()).append("\n");
            content.append("20: ").append(nota.getV20()).append("\n");
            content.append("Moedas: ").append(nota.getMoedas()).append("\n");
            content.append("-----------------------------------\n");
            content.append("TOTAL: ").append(nota.getCard()).append("\n");
            content.append("Total: ").append(total).append("\n");
            content.append("-----------------------------------\n");
            content.append("TOTAL Vendido: ").append(txtValorTotalVenda.getText()).append("\n");
            content.append("Total Recebido: ").append(total).append("\n");
            content.append("Diferença: ").append(diferenca).append("\n");
            content.append("-----------------------------------\n");
            content.append("             ASSINATURA            \n");
            content.append("___________________________________\n");

            // Enviar para a impressora
            PrintService defaultPrintService = PrintServiceLookup.lookupDefaultPrintService();
            DocPrintJob job = defaultPrintService.createPrintJob();
            SimpleDoc doc = new SimpleDoc(content.toString().getBytes(), DocFlavor.BYTE_ARRAY.AUTOSENSE, null);
            job.print(doc, null);
        } catch (PrintException ex) {
            Logger.getLogger(FrmContabilista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtValorCard = new javax.swing.JTextField();
        txtValor1000 = new javax.swing.JTextField();
        txtValor500 = new javax.swing.JTextField();
        txtValor200 = new javax.swing.JTextField();
        txtValor100 = new javax.swing.JTextField();
        txtValor50 = new javax.swing.JTextField();
        txtValor20 = new javax.swing.JTextField();
        txtMoedas = new javax.swing.JTextField();
        txtNomeCom = new javax.swing.JTextField();
        txtValorTotalVenda = new javax.swing.JTextField();
        jbtSet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fecho");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(51, 255, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("1000");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("500");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("200");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("100");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("50");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("20");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Cartões:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Moedas");

        txtValorCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorCardActionPerformed(evt);
            }
        });

        txtValor1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValor1000ActionPerformed(evt);
            }
        });

        txtValor500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValor500ActionPerformed(evt);
            }
        });

        txtValor200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValor200ActionPerformed(evt);
            }
        });

        txtValor100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValor100ActionPerformed(evt);
            }
        });

        txtValor50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValor50ActionPerformed(evt);
            }
        });

        txtValor20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValor20ActionPerformed(evt);
            }
        });

        txtMoedas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMoedasActionPerformed(evt);
            }
        });

        txtNomeCom.setEditable(false);

        txtValorTotalVenda.setEditable(false);

        jbtSet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/finalizar-foco.png"))); // NOI18N
        jbtSet.setText("Finalize");
        jbtSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtNomeCom, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtValorTotalVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel12))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtValorCard, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jbtSet)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtValor1000, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtValor500, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtValor200, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtValor100, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtValor50, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtValor20, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtMoedas, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 33, Short.MAX_VALUE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtValorCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtValor1000, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtValor500, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtValor200, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtValor100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtValor50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMoedas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(29, 29, 29)
                .addComponent(jbtSet)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValorCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorCardActionPerformed
        txtValor1000.requestFocus();
    }//GEN-LAST:event_txtValorCardActionPerformed

    private void txtValor1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValor1000ActionPerformed
        txtValor500.requestFocus();
    }//GEN-LAST:event_txtValor1000ActionPerformed

    private void txtValor500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValor500ActionPerformed
        txtValor200.requestFocus();
    }//GEN-LAST:event_txtValor500ActionPerformed

    private void txtValor200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValor200ActionPerformed
        txtValor100.requestFocus();
    }//GEN-LAST:event_txtValor200ActionPerformed

    private void txtValor100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValor100ActionPerformed
        txtValor50.requestFocus();
    }//GEN-LAST:event_txtValor100ActionPerformed

    private void txtValor50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValor50ActionPerformed
        txtValor20.requestFocus();
    }//GEN-LAST:event_txtValor50ActionPerformed

    private void txtValor20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValor20ActionPerformed
        txtMoedas.requestFocus();
    }//GEN-LAST:event_txtValor20ActionPerformed

    private void jbtSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSetActionPerformed
        try {
            cartoes = Double.parseDouble(txtValorCard.getText());
            valor1000 = Integer.parseInt(txtValor1000.getText());
            valor500 = Integer.parseInt(txtValor500.getText());
            valor200 = Integer.parseInt(txtValor200.getText());
            valor100 = Integer.parseInt(txtValor100.getText());
            valor50 = Integer.parseInt(txtValor50.getText());
            valor20 = Integer.parseInt(txtValor20.getText());          
            moeda = Float.parseFloat(txtMoedas.getText());
            
            double totallocal = (cartoes + valor1000 + valor500 + valor200 + valor100 + valor50 + valor20 + moeda);
            double diferenca = total - totallocal;
            FechoDAO fechoDao = new FechoDAO();
            
            Notas nota = new Notas();
            nota.setCard(cartoes);
            nota.setV1000(valor1000);
            nota.setV500(valor500);
            nota.setV200(valor200);
            nota.setV100(valor100);
            nota.setV50(valor50);
            nota.setV20(valor20);
            nota.setMoedas(moeda);
            
            nota.setId(idn);
            fechoDao.updateNotas(nota);

            Fecho f = fechoDao.retornarFecho(nome);
            if (f != null) {
                f.setValorFalta(diferenca);
                f.setId(id);
                fechoDao.updateFecho(f);
            } 
            ((FrmContabilista) getParent()).readJTable();
            //sentToPrinter(cartoes, nota, diferenca);
            txtNomeCom.setText("");
            txtValorTotalVenda.setText("");
            txtValorCard.setText("");
            txtValor1000.setText("");
            txtValor500.setText("");
            txtValor200.setText("");
            txtValor100.setText("");
            txtValor50.setText("");
            txtValor20.setText("");
            txtMoedas.setText("");
            dispose();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }


    }//GEN-LAST:event_jbtSetActionPerformed

    private void txtMoedasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMoedasActionPerformed
        jbtSetActionPerformed(evt);
    }//GEN-LAST:event_txtMoedasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtSet;
    private javax.swing.JTextField txtMoedas;
    private javax.swing.JTextField txtNomeCom;
    private javax.swing.JTextField txtValor100;
    private javax.swing.JTextField txtValor1000;
    private javax.swing.JTextField txtValor20;
    private javax.swing.JTextField txtValor200;
    private javax.swing.JTextField txtValor50;
    private javax.swing.JTextField txtValor500;
    private javax.swing.JTextField txtValorCard;
    private javax.swing.JTextField txtValorTotalVenda;
    // End of variables declaration//GEN-END:variables

    /**
     * @param valor1000 the valor1000 to set
     */
    public void setValor1000(int valor1000) {
        this.valor1000 = valor1000;
        txtValor1000.setText(valor1000 + "");
    }

    /**
     * @param valor500 the valor500 to set
     */
    public void setValor500(int valor500) {
        this.valor500 = valor500;
        txtValor500.setText(valor500 + "");
    }

    /**
     * @param valor200 the valor200 to set
     */
    public void setValor200(int valor200) {
        this.valor200 = valor200;
        txtValor200.setText(valor200 + "");
    }

    /**
     * @param valor100 the valor100 to set
     */
    public void setValor100(int valor100) {
        this.valor100 = valor100;
        txtValor100.setText(valor100 + "");
    }

    /**
     * @param valor50 the valor50 to set
     */
    public void setValor50(int valor50) {
        this.valor50 = valor50;
        txtValor50.setText(valor50 + "");
    }

    /**
     * @param valor20 the valor20 to set
     */
    public void setValor20(int valor20) {
        this.valor20 = valor20;
        txtValor20.setText(valor20 + "");
    }

    /**
     * @param cartoes the cartoes to set
     */
    public void setCartoes(double cartoes) {
        this.cartoes = cartoes;
        txtValorCard.setText(cartoes + "");
    }

    /**
     * @param moeda the moeda to set
     */
    public void setMoeda(float moeda) {
        this.moeda = moeda;
        txtMoedas.setText(moeda + "");
    }

    /**
     * @param nome the nome to set
     */
    public void setNome(String nome) {
        this.nome = nome;
        txtNomeCom.setText(nome);
    }

    /**
     * @param total the total to set
     */
    public void setTotal(double total) {
        this.total = total;
        txtValorTotalVenda.setText(total + "");
    }

}
